apiVersion: apps/v1
kind: Deployment
metadata:
  name: poi-svc-deployment
  labels:
    app: poi-svc-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: poi-svc-deployment
  template:
    metadata:
      labels:
        app: poi-svc-deployment
    spec:
      containers:
      - name: poi
        image: registryayb1330.azurecr.io/openhacks-vlad/poi:v1
        ports:
        - containerPort: 80