apiVersion: apps/v1
kind: Deployment
metadata:
  name: userprofile-svc-deployment
  namespace: api-dev-namespace
  labels:
    app: userprofile
spec:
  replicas: 5
  selector:
    matchLabels:
      app: userprofile
  template:
    metadata:
      labels:
        app: userprofile
    spec:
      containers:
        - name: userprofile
          image: registryayb1330.azurecr.io/openhacks-vlad/userprofile:v1
          ports:
            - containerPort: 80
          env:
            - name: SQL_SERVER
              value: "sqlserverayb1330.database.windows.net"
            - name: SQL_USER
              value: "sqladminaYb1330"
            - name: SQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: openhack-secret
                  key: SQL_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: userprofile-svc
  namespace: api-dev-namespace
  labels:
    app: userprofile
spec:
  ports:
    - port: 80
      protocol: TCP
  selector:
    app: userprofile
